Fix AttributeError: 'int' object has no attribute 'node' due to constant prop
Fixes https://github.com/pytorch/pytorch/issues/140625

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

ghstack-source-id: bcb22c67950ceae99778b03fe0de2cfcca6d0937
Pull Request resolved: https://github.com/pytorch/pytorch/pull/141250